### ISSUE TITLE
Version 0.2.3 has breaking changes

### ISSUE THREAD

**Issue by timothee-haudebourg** [Cybersecurity-LINKS/zkryptium#8]
Hi, first of all thank you for developing this great library that has been very useful for us in [`ssi`](https://github.com/spruceid/) to implement the [BBS-based W3C Data-Integrity cryptosuite](https://www.w3.org/TR/vc-di-bbs/#bbs-2023).

I see you released a new version 0.2.3 including #6 and #7. #6 changes the specification of two types whiles #7 changes the specification of the signature algorithm itself. These are breaking changes that will impact the dependents of this library. As you can see [here](https://github.com/spruceid/ssi/actions/runs/10940970778/job/30421782304), it did break our tests.

Would you consider yanking version 0.2.3 and release a new minor version (0.3) instead?

**Comment by AlbertoSvg** [comment]
Hi @timothee-haudebourg thank you for your feedback. I did what you suggested and released the changes as a new minor version.
